name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'   # Trigger the pipeline for version tags (e.g., v1.0.0)
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          coverage run -m pytest  # Ejecuta los tests de pytest con cobertura
          coverage report  # Muestra el informe de cobertura

      - name: Run normal tests (test_app.py)
        run: |
          pytest test_app.py  # Ejecuta los tests definidos en test_app.py

      - name: Lint code
        run: flake8 .  # Lintea el código con flake8

  docker-build:
    runs-on: ubuntu-latest
    needs: test-and-lint  # Este job solo se ejecutará si 'test-and-lint' es exitoso
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag task_manager_api:latest

  docker-publish:
    runs-on: ubuntu-latest
    needs: docker-build  # Este job solo se ejecutará si 'docker-build' es exitoso
    if: startsWith(github.ref, 'refs/tags/')  # Solo se ejecuta cuando se hace push de un tag (por ejemplo: v1.0.0)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/task_manager_api:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/task_manager_api:latest